package main

import (
	//"fmt"
	"github.com/gin-gonic/gin"
	_ "./docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"
	"webgo/apps/userprofile/view"
	"webgo/log"
	"webgo/setting"
	"webgo/apps/userprofile/middlewares"
)

func main() {
	// Add a logger
	var logger log.Logging
	logger.GetLogger()
	defer logger.Close()

	// Load config
	var config setting.Config
	config.LoadConfig()

	// get orm engine

	/*
	user.Username = "dongxy"
	user.Password = "sk927312*"
	user.Email = "870428371@qq.com"
	user.Address = "beijing"
	birthday, _ := time.Parse("2006-01-02", "1992-03-13")
	user.Birthday = birthday
	user.CreatedAt, _ = time.Parse("2006-01-02 15:04:05", time.Now().Format("2006-01-02 15:04:05"))
	fmt.Println(user)
	affected, err := dbEngine.Insert(user)
	fmt.Println(affected)
	*/

	r := gin.Default()

	v1 := r.Group("api/v1")
	{
		v1.POST("user/register", view.RegisterView)
		v1.POST("user/login", view.LoginView)
		v1.POST("user/delete", view.DeleteAccountView)
	}

	test := r.Group("api/test")
	test.Use(middlewares.JWTAuth())
	{
		test.GET("getdatabytime", view.GetDataByTime)
	}

	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	r.Run(":8080")
}



